"""empty message

Revision ID: 104513e05093
Revises: 9dd0a7426144
Create Date: 2016-06-08 15:05:38.537000

"""

# revision identifiers, used by Alembic.
revision = '104513e05093'
down_revision = '9dd0a7426144'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('Contact', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'Contact')
    ### end Alembic commands ###
