"""empty message

Revision ID: e77fbb7c9243
Revises: 13aa27ac986e
Create Date: 2016-05-31 16:57:14.166000

"""

# revision identifiers, used by Alembic.
revision = 'e77fbb7c9243'
down_revision = '13aa27ac986e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
